function SVNwidget(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',zc='.cache.html',_='/',$b='023FB83B89CAB112D67A9E03B4BF38CD',ac='0D29B6BA1BC284702018DE6A38F10AE4',bc='0F46FF717B993F0DD408B7699892B61E',cc='1314C280489A1BA45275AD605EE4F96E',dc='172C09FBB54D3DCDCF65D91B12831759',ec='1E3E10CA51BC6A82F5F7E67E459DAEC8',fc='25E84A61087615ED09EA28A8D45FE8F5',gc='268E953715E78A76D9BC9C451F38A130',hc='27C43F9854676550A33542A3F447B4AA',ic='2A919996350752A58B7E838F25D0BD1E',jc='2FE433E530BA3CDB9410869E1DE3345C',lc='33A3BC8F7E35453522DD7DC844F2FC6F',mc='4486012BDA45763FE31DB8E2BC0A9C25',nc='473AB87D4C937EC4FF491FC006C9036F',oc='4CE3BA9DFE6ED7B77AA375A0637B67BE',pc='555C84A6037B2364D62DEA83DE6694E2',qc='732136E3709B1954295E39EC971CC79A',yc=':',ob='::',Ec='<script defer="defer">SVNwidget.onInjectionDone(\'SVNwidget\')<\/script>',hb='<script id="',Cc='<script language="javascript" src="',rb='=',$='?',rc='A48B316C9C1ACDB6702043A96AA0FBD7',Mb='ActiveXObject',tb='Bad handler "',sc='CA5625E5B4F74C237BCBE3F6A7EF105E',tc='CBCE06AA11A5CF332CCE29A2B4A45222',Nb='ChromeTab.ChromeFrame',uc='D3040EA5CB405A34EB56C3555CFB5B28',Ac='DOMContentLoaded',vc='F1B0F52DB6E7B482A4B5F751145CDF09',wc='F1DEB454A9729BF3E2B9673E102AE273',xc='F36600434CE5A366A87795916FE19AA9',jb='SCRIPT',Q='SVNwidget',eb='SVNwidget.nocache.js',nb='SVNwidget::',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_SVNwidget',kb='base',cb='baseUrl',T='begin',S='bootstrap',Lb='chromeframe',bb='clear.cache.gif',qb='content',_b='cs',kc='default',Zb='en',Y='end',Tb='gecko',Ub='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Xb='hosted.html?SVNwidget',Sb='ie6',Rb='ie8',Qb='ie9',xb='iframe',ab='img',yb="javascript:''",Bc='jsonpath.js',Dc='jsonpath.js"><\/script>',Wb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Pb='msie',mb='name',Jb='opera',zb='position:absolute;width:0;height:0;border:none',Ob='safari',db='script',Yb='selectingPermutation',Cb='sl',R='startup',fb='undefined',Vb='unknown',Ib='user.agent',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}SVNwidget=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={cs:0,'default':1,en:2,sl:3};v[Ib]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(Jb)!=-1}())return Jb;if(function(){return c.indexOf(Kb)!=-1||function(){if(c.indexOf(Lb)!=-1){return true}if(typeof window[Mb]!=fb){try{var b=new ActiveXObject(Nb);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Ob;if(function(){return c.indexOf(Pb)!=-1&&m.documentMode>=9}())return Qb;if(function(){return c.indexOf(Pb)!=-1&&m.documentMode>=8}())return Rb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Sb;if(function(){return c.indexOf(Tb)!=-1}())return Ub;return Vb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};SVNwidget.onScriptLoad=function(){if(I){q=true;B()}};SVNwidget.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Xb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Yb});if(!A()){try{G([Zb,Jb],$b);G([_b,Ub],ac);G([Zb,Ub],bc);G([Zb,Rb],cc);G([Cb,Jb],dc);G([_b,Ob],ec);G([_b,Qb],fc);G([Zb,Qb],gc);G([Zb,Sb],hc);G([_b,Rb],ic);G([Cb,Qb],jc);G([kc,Ub],lc);G([_b,Sb],mc);G([kc,Ob],nc);G([kc,Rb],oc);G([Cb,Sb],pc);G([Zb,Ob],qc);G([kc,Qb],rc);G([Cb,Rb],sc);G([Cb,Ob],tc);G([kc,Jb],uc);G([Cb,Ub],vc);G([_b,Jb],wc);G([kc,Sb],xc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(yc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+zc}catch(a){return}}var N;function O(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(Ac,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Ac,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:T});if(!__gwt_scriptsLoaded[Bc]){__gwt_scriptsLoaded[Bc]=true;document.write(Cc+s+Dc)}m.write(Ec)}
SVNwidget();
